CREATE TABLE lamps (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lamp_number INT NOT NULL,
  is_lit TINYINT(1) DEFAULT 0
);

-- Insert 25 lamps initially
INSERT INTO lamps (lamp_number, is_lit)
SELECT n, 0 FROM (
  SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
  UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
  UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
) t;
-- Ensure lamp_number is unique